# Setup
title:               Attacking Contrastive Models
tagline:             'A blog post for 6.S898.'
description:         'Blogging on contrastive learning.'
url:                 https://jpaynter.github.io/iclr-blog-track.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jon Paynter
  url:               https://jpaynter.github.io/iclr-blog-track.github.io/
  email:             jpaynter@mit.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15

theme: jekyll-theme-minimal
