# Setup
title:               Jon Paynter
tagline:             'Posting for 6.S898.'
description:         'An initial blog post!'
url:                 https://jpaynter.github.io/attacking-CLIP-blog/
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jon Paynter
  url:               https://jpaynter.github.io/attacking-CLIP-blog/
  email:             jpaynter@mit.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15

theme: jekyll-theme-minimal
