# Setup
title:               Attacking a Contrastive Model
tagline:             'A Short Summary of: Poisoning and Backdooring Contrastive Learning'
description:         'A blog post for 6.867, fall 2021.'
url:                 ''
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Jon Paynter
  url:               ''
  email:             jpaynter@mit.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15

theme: jekyll-theme-minimal
